/**
 * Audio delivery.
 *
 * Production audio is served from the Jubilee CDN / streaming pipeline. Until
 * masters land, every track points at a single ambient placeholder so the
 * transport, the waveform, the scrubber, and playback-position persistence can
 * all be exercised end to end against a real <audio> element.
 *
 * THE PLACEHOLDER IS NOT MUSIC. It is a synthesized drone, generated by
 * `scripts/generate-placeholder-audio.mjs`. Swap `audioUrl` on each Track for
 * the real CDN URL and nothing else changes.
 */

export const PLACEHOLDER_AUDIO = '/audio/placeholder-ambient.wav';

/**
 * Build a track's stable id. Saved playback positions are keyed by it, so it
 * lives here — in one place — rather than being spelled out at each call site.
 */
export function trackId(albumSlug: string, n: number): string {
  return `${albumSlug}:${n}`;
}

/** True when a URL is the stand-in rather than a real master. */
export function isPlaceholder(url: string | null): boolean {
  return url === PLACEHOLDER_AUDIO;
}

/**
 * Resolve a content audio URL to something playable.
 * Set NEXT_PUBLIC_JUBILEE_CDN to prefix relative CDN keys in production.
 */
export function resolveAudio(url: string | null): string | null {
  if (!url) return null;
  if (url.startsWith('http') || url.startsWith('/')) return url;
  const cdn = process.env.NEXT_PUBLIC_JUBILEE_CDN;
  return cdn ? `${cdn.replace(/\/$/, '')}/${url}` : null;
}
